# Generated by Django 4.0.6 on 2022-07-20 10:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('quizapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='address1',
            field=models.CharField(default=django.utils.timezone.now, max_length=122),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='candidate',
            name='address2',
            field=models.CharField(default=django.utils.timezone.now, max_length=122),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='candidate',
            name='city',
            field=models.CharField(default=django.utils.timezone.now, max_length=22),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='candidate',
            name='email',
            field=models.CharField(default=django.utils.timezone.now, max_length=122),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='candidate',
            name='firstname',
            field=models.CharField(default=django.utils.timezone.now, max_length=122),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='candidate',
            name='lastname',
            field=models.CharField(default=django.utils.timezone.now, max_length=122),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='candidate',
            name='state',
            field=models.CharField(default=django.utils.timezone.now, max_length=22),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='candidate',
            name='zip',
            field=models.CharField(default=django.utils.timezone.now, max_length=22),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='questionmaker',
            name='address1',
            field=models.CharField(default=django.utils.timezone.now, max_length=122),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='questionmaker',
            name='address2',
            field=models.CharField(default=django.utils.timezone.now, max_length=122),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='questionmaker',
            name='city',
            field=models.CharField(default=django.utils.timezone.now, max_length=22),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='questionmaker',
            name='email',
            field=models.CharField(default=django.utils.timezone.now, max_length=122),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='questionmaker',
            name='firstname',
            field=models.CharField(default=django.utils.timezone.now, max_length=122),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='questionmaker',
            name='lastname',
            field=models.CharField(default=django.utils.timezone.now, max_length=122),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='questionmaker',
            name='state',
            field=models.CharField(default=django.utils.timezone.now, max_length=22),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='questionmaker',
            name='zip',
            field=models.CharField(default=django.utils.timezone.now, max_length=22),
            preserve_default=False,
        ),
    ]
