# Generated by Django 4.0.6 on 2022-07-20 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizapp', '0003_rename_zip_questionmaker_zipc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionmaker',
            name='city',
            field=models.CharField(max_length=122),
        ),
    ]
