# Generated by Django 4.0.6 on 2022-07-21 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizapp', '0004_alter_questionmaker_city'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=122)),
                ('lastname', models.CharField(max_length=122)),
                ('email', models.CharField(max_length=122)),
                ('password', models.CharField(max_length=30)),
                ('address1', models.CharField(max_length=122)),
                ('address2', models.CharField(max_length=122)),
                ('city', models.CharField(max_length=122)),
                ('state', models.CharField(max_length=22)),
                ('zipc', models.CharField(max_length=22)),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=122)),
                ('lastname', models.CharField(max_length=122)),
                ('email', models.CharField(max_length=122)),
                ('password', models.CharField(max_length=30)),
                ('address1', models.CharField(max_length=122)),
                ('address2', models.CharField(max_length=122)),
                ('city', models.CharField(max_length=22)),
                ('state', models.CharField(max_length=22)),
                ('zip', models.CharField(max_length=22)),
                ('date', models.DateField()),
            ],
        ),
        migrations.DeleteModel(
            name='Candidate',
        ),
        migrations.DeleteModel(
            name='Questionmaker',
        ),
    ]
